sudo: required
services:
  - docker

before_install:
  - docker build -t adeyems/multi-docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adeyems/multi-docker-react-test npm test -- --coverage

after_success:
  - docker build -t adeyems/multi-docker-client ./client
  - docker build -t adeyems/multi-docker-nginx ./nginx
  - docker build -t adeyems/multi-docker-server ./server
  - docker build -t adeyems/multi-docker-worker  ./worker

  - echo "$DOCKER_PWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push adeyems/multi-docker-client
  - docker push adeyems/multi-docker-nginx
  - docker push adeyems/multi-docker-server
  - docker push adeyems/multi-docker-worker



