sudo: required
services:
  - docker

#env:
  #global:
   # - SHA=$(git rev-parse HEAD)
    #- CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  #- openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  #- curl https://sdk.cloud.google.com | bash > /dev/null;
  #- source $HOME/google-cloud-sdk/path.bash.inc
  #- gcloud components update kubectl
  #- gcloud auth activate-service-account --key-file service-account.json
  #- gcloud config set project skilful-berm-214822
  #- gcloud config set compute/zone us-central1-a
  #- gcloud container clusters get-credentials multi-cluster
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t adeyems/multi-docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adeyems/multi-docker-react-test npm test -- --coverage

after_success:
  - docker build -t adeyems/multi-docker-client ./client
  - docker build -t adeyems/multi-docker-nginx ./nginx
  - docker build -t adeyems/multi-docker-server ./server
  - docker build -t adeyems/multi-docker-worker  ./worker

#login to docker
- echo "$DOCKER_PWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #push the images to docker hub
  - docker push adeyems/multi-docker-client
  - docker push adeyems/multi-docker-nginx
  - docker push adeyems/multi-docker-server
  - docker push adeyems/multi-docker-worker


